# Generated by Django 5.0.6 on 2024-06-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_countryname_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='countryName',
            field=models.CharField(default='India', max_length=20),
        ),
    ]
