# Generated by Django 5.0.6 on 2024-06-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_user_countryname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='countryName',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
