# Generated by Django 5.0.6 on 2024-07-01 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcategory', models.CharField(choices=[('Sofa', 'Sofa'), ('Coffee Table', 'Coffee Table'), ('TV Stand', 'TV Stand'), ('Armchair', 'Armchair'), ('Bookshelf', 'Bookshelf'), ('Bed Frame', 'Bed Frame'), ('Mattress', 'Mattress'), ('Mirror', 'Mirror'), ('Dining Table', 'Dining Table'), ('Sideboard', 'Sideboard'), ('Server Table', 'Server Table'), ('Dining Chairs', 'Dining Chairs')], max_length=50)),
                ('productname', models.CharField(max_length=50)),
                ('pprice', models.PositiveIntegerField()),
                ('pdesc', models.TextField()),
                ('productimage', models.ImageField(default='', upload_to='picture/pimages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
