# Generated by Django 5.0.6 on 2024-07-09 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='time_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 9, 2, 32, 31, 763194, tzinfo=datetime.timezone.utc)),
        ),
    ]
