# Generated by Django 5.0.6 on 2024-07-11 02:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_wishlist_time_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='time_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 2, 3, 47, 947993, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_date', models.DateTimeField(default=datetime.datetime(2024, 7, 11, 2, 3, 47, 947993, tzinfo=datetime.timezone.utc))),
                ('payment', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
