# Generated by Django 5.0.6 on 2024-07-11 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_wishlist_time_date_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='time_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 3, 34, 37, 543708, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='time_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 3, 34, 37, 543708, tzinfo=datetime.timezone.utc)),
        ),
    ]
