# Generated by Django 5.0.6 on 2024-07-13 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_cart_qty_cart_total_alter_cart_time_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='roundtotal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='time_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 3, 23, 39, 242019, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='time_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 3, 23, 39, 241023, tzinfo=datetime.timezone.utc)),
        ),
    ]
