# Generated by Django 5.0.7 on 2024-07-20 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_institute', '0003_rename_department_teacher_compensation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='founded_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='club',
            name='members_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='club',
            name='president',
            field=models.CharField(default='Default President', max_length=200),
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(default='Default description'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(default='Default Club Name', max_length=100),
        ),
    ]
