# Generated by Django 5.0.7 on 2024-07-23 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_institute', '0006_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usertype',
        ),
    ]
